import openai
from io import BytesIO
from PIL import Image
import base64
import os
import json
from utils import crop_difference_region
import re

# Load from environment variable
openai.api_key = os.getenv("OPENAI_API_KEY")

def image_to_base64(img: Image.Image):
    buffer = BytesIO()
    img.save(buffer, format="PNG")
    return base64.b64encode(buffer.getvalue()).decode("utf-8")

def call_vlm_agent(current_img, target_img, program_code):
    """
    Uses OpenAI GPT-4V to suggest an edit to the syntax tree
    given the current and target images.
    """
    current_b64 = image_to_base64(current_img)
    target_b64 = image_to_base64(target_img)

    prompt = f"""
You are editing a shape-based program that generates images.

Current program:
{program_code}

Your task: suggest ONE structured edit to make the rendered image match the **target image**.

Edit format MUST be one of:

1. Insert:
{{
  "action": "insert_child",
  "target_path": [],
  "new_node": {{
    "type": "Square", "x": 50, "y": 50, "size": 20
  }}
}}

2. Modify:
{{
  "action": "modify_param",
  "target_path": [0],
  "param": "x",
  "value": 30
}}

ONLY respond with the JSON object — no explanation, no markdown.
"""

    messages = [
        {"role": "system", "content": "You are a VLM agent that edits shape-based programs to match target images."},
        {"role": "user", "content": [
            {"type": "text", "text": prompt},
            {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{current_b64}"}},
            {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{target_b64}"}}
        ]}
    ]

    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        max_tokens=500,
        temperature=0.2
    )

    content = response.choices[0].message.content.strip()

    # Handle different formats of the output
    if content.startswith("```json"):
        content = content.split("```json")[1].split("```")[0].strip()
    elif content.startswith("```"):
        content = content.split("```")[1].split("```")[0].strip()

    # Then try to parse it
    edit = json.loads(content)

    # Parse the JSON output
    try:
        edit = json.loads(content)
        return {"thought": "Generated by GPT-4V", "edit": edit}
    except Exception as e:
        raise ValueError(f"Failed to parse agent output:\n{content}") from e

def call_vlm_agent_with_reflexion(current_img, target_img, program_code, prev_iou, current_iou):
    current_b64 = image_to_base64(current_img)
    target_b64 = image_to_base64(target_img)
    diff_crop = crop_difference_region(current_img, target_img)
    diff_b64 = image_to_base64(diff_crop)

    improved = current_iou > prev_iou
    feedback = "Good progress ✅ IoU improved." if improved else "Failed ⚠️ — IoU dropped or unchanged."

    prompt = f"""
You are improving a shape-based image synthesis program.

Previous IoU: {prev_iou:.3f}
Current IoU: {current_iou:.3f}
Feedback: {feedback}

Also shown is a **highlighted diff region** — the area where the current image differs from the target.
Focus your edit suggestion in this area.

Here is the current program:
{json.dumps(program_code, indent=2)}

Step-by-step:
1. Briefly explain **why** the current output differs from the target. (Thought)
2. You must suggest ONE atomic **edit**, not a full program.

Valid edit formats (JSON with an "action" key):

Insert:
{{
  "action": "insert_child",
  "target_path": [],
  "new_node": {{
    "type": "Circle" | "Square",
    "x": int, "y": int, "r" or "size": int
  }}
}}

Modify:
{{
  "action": "modify_param",
  "target_path": [int, ...],
  "param": "x" | "y" | "r" | "size",
  "value": int
}}

Output format:
Thought: <your reasoning here>

```json
<your proposed edit here>
"""

    messages = [
    {"role": "system", "content": "You are a VLM agent that edits shape programs to match target images."},
    {"role": "user", "content": [
        {"type": "text", "text": prompt},
        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{current_b64}", "detail": "low"}},
        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{target_b64}", "detail": "low"}},
        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{diff_b64}", "detail": "high"}},
    ]}
]

    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        max_tokens=500,
        temperature=0.2
    )

    content = response.choices[0].message.content.strip()

    # Extract thought and edit using regex
    thought_match = re.search(r"Thought:\s*(.*?)\n```", content, re.DOTALL)
    json_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", content, re.DOTALL)

    if not json_match:
        raise ValueError(f"Could not parse agent response:\n{content}")

    thought = thought_match.group(1).strip() if thought_match else "No thought provided"
    edit = json.loads(json_match.group(1))

    return {"thought": thought, "edit": edit}

